-- ============================================================================
-- Migration 0039: create_guard_with_person
-- ============================================================================
-- Purpose:
--   Atomically create a guard: person row + guard_profile row in one
--   transaction. The guard_code is generated by the trigger set_guard_code
--   (migration 0007) — we insert an empty string, the trigger replaces it,
--   and the return clause reads back the final value.
--
-- Design decisions locked:
--   - Guards do NOT get an account. They log in with shift_code + guard_code
--     via /api/guard-session/start. Adding account-based guard auth is a
--     v2 concern and not needed for the current flow.
--   - guard status starts as 'active' — there is no separate acceptance step
--     because the guard does not need to accept anything. Admin deactivates
--     later when the guard leaves.
--   - Full name is required (handoff §15 — a guard must be identifiable).
--   - phone and email are optional.
--
-- Error codes:
--   NOT_AUTHENTICATED
--   NOT_AUTHORIZED
--   SUBSCRIPTION_INACTIVE
--   FULL_NAME_REQUIRED
-- ============================================================================

create or replace function public.create_guard_with_person(
  p_organization_id uuid,
  p_full_name       text,
  p_phone           text default null,
  p_email           text default null
)
returns table (
  guard_profile_id uuid,
  person_id        uuid,
  guard_code       text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_account_id  uuid;
  v_person_id   uuid;
  v_guard_id    uuid;
  v_guard_code  text;
  v_phone       text;
  v_email       text;
begin
  -- 1. Caller must be authenticated.
  v_account_id := public.current_account_id();
  if v_account_id is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;

  -- 2. Caller must be an admin of the target org.
  if not public.is_org_admin(p_organization_id) then
    raise exception 'NOT_AUTHORIZED';
  end if;

  -- 3. Org must be operational. SECURITY DEFINER bypasses the RLS
  --    subscription lock, so we self-enforce it here.
  if not public.is_org_operational(p_organization_id) then
    raise exception 'SUBSCRIPTION_INACTIVE';
  end if;

  -- 4. Validate input.
  if p_full_name is null or length(btrim(p_full_name)) = 0 then
    raise exception 'FULL_NAME_REQUIRED';
  end if;

  -- Normalise optional fields to NULL when blank.
  v_phone := nullif(btrim(coalesce(p_phone, '')), '');
  v_email := nullif(btrim(coalesce(p_email, '')), '');

  -- 5. Create the person.
  v_person_id := public.uuidv7();
  insert into public.people (
    id, organization_id, full_name, phone, email, status, created_by
  ) values (
    v_person_id, p_organization_id, btrim(p_full_name), v_phone, v_email,
    'active', v_account_id
  );

  -- 6. Create the guard profile. Empty guard_code triggers auto-generation
  --    in set_guard_code (migration 0007). The RETURNING clause captures the
  --    post-trigger value so we do not need a second SELECT.
  v_guard_id := public.uuidv7();
  insert into public.guard_profiles (
    id, organization_id, person_id, guard_code, status, created_by
  ) values (
    v_guard_id, p_organization_id, v_person_id, '', 'active', v_account_id
  )
  returning guard_code into v_guard_code;

  -- 7. Return the created rows' identifiers and the generated code.
  return query select v_guard_id, v_person_id, v_guard_code;
end;
$$;

comment on function public.create_guard_with_person(uuid, text, text, text) is
  'Atomically creates a person + guard_profile. Guard code auto-generated by trigger. Guard starts as active. No account — guards log in with shift + guard codes.';
