-- ============================================================================
-- Migration 0040: fix guard_code ambiguity in create_guard_with_person
-- ============================================================================
-- Bug in migration 0039:
--   The function declares `returns table (..., guard_code text)`, which
--   creates an implicit OUT parameter named `guard_code`. The RETURNING
--   clause in the INSERT reads `returning guard_code`, which plpgsql
--   cannot disambiguate between the OUT parameter and the table column.
--   Error 42702 raised at call time.
--
--   Same class as migration 0031 → 0032 (the household functions). plpgsql
--   function bodies are validated at call time, not CREATE time — the
--   migration applied cleanly and only failed when the function ran.
--
-- Fix:
--   Qualify the column with the table name in the RETURNING clause:
--   `returning public.guard_profiles.guard_code`. Explicit intent, no
--   dependency on plpgsql resolution order.
--
-- No other changes to the function.
-- ============================================================================

create or replace function public.create_guard_with_person(
  p_organization_id uuid,
  p_full_name       text,
  p_phone           text default null,
  p_email           text default null
)
returns table (
  guard_profile_id uuid,
  person_id        uuid,
  guard_code       text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_account_id  uuid;
  v_person_id   uuid;
  v_guard_id    uuid;
  v_guard_code  text;
  v_phone       text;
  v_email       text;
begin
  v_account_id := public.current_account_id();
  if v_account_id is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;

  if not public.is_org_admin(p_organization_id) then
    raise exception 'NOT_AUTHORIZED';
  end if;

  if not public.is_org_operational(p_organization_id) then
    raise exception 'SUBSCRIPTION_INACTIVE';
  end if;

  if p_full_name is null or length(btrim(p_full_name)) = 0 then
    raise exception 'FULL_NAME_REQUIRED';
  end if;

  v_phone := nullif(btrim(coalesce(p_phone, '')), '');
  v_email := nullif(btrim(coalesce(p_email, '')), '');

  v_person_id := public.uuidv7();
  insert into public.people (
    id, organization_id, full_name, phone, email, status, created_by
  ) values (
    v_person_id, p_organization_id, btrim(p_full_name), v_phone, v_email,
    'active', v_account_id
  );

  v_guard_id := public.uuidv7();
  insert into public.guard_profiles (
    id, organization_id, person_id, guard_code, status, created_by
  ) values (
    v_guard_id, p_organization_id, v_person_id, '', 'active', v_account_id
  )
  returning public.guard_profiles.guard_code into v_guard_code;

  return query select v_guard_id, v_person_id, v_guard_code;
end;
$$;

comment on function public.create_guard_with_person(uuid, text, text, text) is
  'Atomically creates a person + guard_profile. Guard code auto-generated by trigger. Guard starts as active. No account — guards log in with shift + guard codes.';
