-- ============================================================================
-- Migration 0046: constraint change + redeem_unit_invite
-- ============================================================================
-- Two changes in one migration, ordered deliberately:
--
-- 1. Change the organization_memberships unique constraint from
--    (organization_id, account_id) to (organization_id, account_id, role).
--
--    Why: an account can legitimately hold multiple roles in the same org —
--    a guard who lives on site, a resident who also helps with admin work.
--    The single-role constraint blocks these real cases the moment they
--    appear. RLS policies check role-specific helpers (is_org_admin,
--    is_org_guard, current_occupied_unit_id) and none assume a single role,
--    so relaxing this constraint has no downstream behavioral impact.
--
-- 2. Add redeem_unit_invite(p_code_hash). Atomic redemption of a unit
--    invite generated by generate_unit_invite (migration 0045). Creates
--    the person row and primary_resident membership, links the account to
--    the occupancy, clears the invite hash. All inside one transaction.
--
-- Order matters: the function uses
--   `on conflict (organization_id, account_id, role) do nothing`
-- which requires the new unique constraint to already exist.
--
-- Errors:
--   NOT_AUTHENTICATED
--   INVITE_INVALID_OR_EXPIRED
--   UNIT_ALREADY_OCCUPIED
--   ALREADY_PRIMARY_RESIDENT
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1. Relax membership uniqueness to allow multiple roles per account/org.
-- ----------------------------------------------------------------------------

alter table public.organization_memberships
  drop constraint organization_memberships_unique_account;

alter table public.organization_memberships
  add constraint organization_memberships_unique_account_role
    unique (organization_id, account_id, role);

comment on constraint organization_memberships_unique_account_role
  on public.organization_memberships is
  'An account may hold multiple roles in the same org. One row per (org, account, role).';


-- ----------------------------------------------------------------------------
-- 2. redeem_unit_invite
-- ----------------------------------------------------------------------------

create or replace function public.redeem_unit_invite(p_code_hash text)
returns table (
  unit_id         uuid,
  organization_id uuid
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_account_id    uuid;
  v_occupancy     record;
  v_org_id        uuid;
  v_unit_id       uuid;
  v_person_id     uuid;
  v_membership_id uuid;
begin
  -- 1. Authenticated caller.
  v_account_id := public.current_account_id();
  if v_account_id is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;

  -- 2. Find and lock the live invite. Match on hash, status, and non-expiry.
  select o.id, o.unit_id, o.invite_expires_at
    into v_occupancy
    from public.occupancies o
   where o.invite_code_hash = p_code_hash
     and o.status = 'invited'
     and o.invite_expires_at > now()
   for update of o;

  if not found then
    raise exception 'INVITE_INVALID_OR_EXPIRED';
  end if;

  v_unit_id := v_occupancy.unit_id;

  -- 3. Resolve organization via unit -> property.
  select p.organization_id into v_org_id
    from public.units u
    join public.properties p on p.id = u.property_id
   where u.id = v_unit_id;

  if v_org_id is null then
    raise exception 'INVITE_INVALID_OR_EXPIRED';
  end if;

  -- 4. Defensive: unit must not already have an active occupancy.
  --    (generate_unit_invite blocks this at creation, but a concurrent
  --    redemption or an out-of-band insert could race.)
  if exists (
    select 1 from public.occupancies
     where unit_id = v_unit_id
       and status = 'active'
  ) then
    raise exception 'UNIT_ALREADY_OCCUPIED';
  end if;

  -- 5. Caller must not already have an active occupancy in this org.
  if exists (
    select 1
      from public.occupancies o
      join public.units u on u.id = o.unit_id
      join public.properties p on p.id = u.property_id
     where o.account_id = v_account_id
       and o.status = 'active'
       and p.organization_id = v_org_id
  ) then
    raise exception 'ALREADY_PRIMARY_RESIDENT';
  end if;

  -- 6. Activate the occupancy. Clear the invite hash (single-use).
  update public.occupancies
     set account_id         = v_account_id,
         status             = 'active',
         started_at         = now(),
         invite_code_hash   = null,
         invite_expires_at  = null
   where id = v_occupancy.id;

  -- 7. Ensure a person row exists for this (account, org). Reuse the
  --    account's display name if no better source is available.
  select id into v_person_id
    from public.people
   where account_id = v_account_id
     and organization_id = v_org_id
   limit 1;

  if v_person_id is null then
    insert into public.people (
      organization_id, account_id, full_name, status
    )
    select v_org_id, v_account_id, coalesce(a.display_name, 'Resident'), 'active'
      from public.accounts a
     where a.id = v_account_id
    returning id into v_person_id;
  end if;

  -- 8. Ensure a primary_resident membership exists. on conflict uses the
  --    new (org, account, role) constraint — idempotent.
  insert into public.organization_memberships (
    organization_id, account_id, role, status, joined_at
  ) values (
    v_org_id, v_account_id, 'primary_resident', 'active', now()
  )
  on conflict (organization_id, account_id, role) do nothing
  returning id into v_membership_id;

  -- 9. Audit — same transaction as the state change.
  perform public.log_audit_event(
    v_org_id,
    v_account_id,
    'unit_invite.redeemed',
    'occupancy',
    v_occupancy.id,
    null,
    jsonb_build_object(
      'unit_id', v_unit_id,
      'person_id', v_person_id
    )
  );

  return query select v_unit_id, v_org_id;
end;
$$;

comment on function public.redeem_unit_invite(text) is
  'Atomically redeems a unit invite: activates occupancy, creates person + primary_resident membership, clears invite hash.';
